name: Formatting check
on: [push, pull_request]
jobs:
  formatting-check:
    name: clang-format style check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
  linter_name:
    name: Python - black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
